puts "Seeding Genres"

consoles = ["macOS",
            "Classic Macintosh",
            "Apple II",
            "Atari 7800",
            "Atari 5200",
            "Atari 2600",
            "Atari Flashback",
            "Atari 8-bit",
            "Atari ST",
            "Atari Lynx",
            "Atari XEGS",
            "Jaguar",
            "Commodore / Amiga",
            "Neo Geo",
            "Nintendo Switch",
            "Nintendo 3DS",
            "Nintendo DS",
            "Nintendo DSi",
            "Wii U",
            "Wii",
            "GameCube",
            "Nintendo 64",
            "Game Boy Advance",
            "Game Boy Color",
            "Game Boy",
            "SNES",
            "NES",
            "PC",
            "PlayStation 5",
            "PlayStation 4",
            "PlayStation 3",
            "PlayStation 2",
            "PlayStation",
            "PS Vita",
            "PSP",
            "Genesis",
            "SEGA Saturn",
            "SEGA CD",
            "SEGA 32X",
            "SEGA Master System",
            "Dreamcast",
            "Game Gear",
            "Xbox One",
            "Xbox Series S/X",
            "Xbox 360",
            "Xbox"]
genres = ["2D Fighting",
          "3D Fighting",
          "4X Strategy",
          "Action",
          "Action-Adventure",
          "Action-RPG",
          "Adventure",
          "Air Combat",
          "Arena Brawler",
          "Arena Combat",
          "Arena Shooter",
          "Artillery",
          "Atmospheric",
          "Beat-'em-Up",
          "Board Game",
          "Bullet Hell",
          "Card Game",
          "Casual",
          "Character Action",
          "CMS",
          "Collect-a-thon",
          "Combat",
          "Dating Sim",
          "Dungeon Crawler",
          "Edutainment",
          "Endless Runner",
          "Escape the Room",
          "FPS",
          "Grand Strategy",
          "Hack-n-Slash",
          "Incremental",
          "Interactive Fiction",
          "Interactive Movie",
          "JRPG",
          "Kart Racing",
          "Kusoge",
          "Life Sim",
          "Light Gun",
          "Matching Puzzle",
          "Maze",
          "Mech Combat",
          "Metroidvania",
          "Military Sim",
          "Mini-games",
          "MMO",
          "MOBA",
          "Monster Collecting",
          "Musou",
          "Open World",
          "Paddle",
          "Party",
          "Physics Puzzle",
          "Platform",
          "Puzzle",
          "Programming",
          "Pro Wrestling",
          "Racing",
          "Rail Shooter",
          "Raising Sim",
          "Rhythm",
          "Roguelike",
          "RPG",
          "RTS",
          "Run-n-Gun",
          "Shoot 'em Up",
          "Shooting",
          "Sim",
          "Sports",
          "SRPG",
          "Stealth",
          "Strategy",
          "Survival",
          "Survival Horror",
          "TBS",
          "TCG",
          "Time Management",
          "Tower Defense",
          "TPS",
          "Vehicular Combat",
          "Vehicular Sim",
          "Visual Novel",
          "Walking Simulator",
          "WRPG"]
if Genre.count == 0
  genres.each do |genre|
    Genre.create(name: genre)
  end
end

puts "Seeding Consoles"

if Console.count == 0
  consoles.each do |console|
    Console.create(name: console)
  end
end

puts "Seeding Collectors"

tony = Collector.create(name: "Tony")

puts "Done Seeding"
